import React, { useState } from "react";
import { Typography } from "antd";
import {
  getCuratedGraph,
  getConnectedNodes,
  duplicateMutlilocationNodes,
} from "./utils/graph";
import Cell from "./components/cell";
import Definition from "./components/definition-box";
import "antd/dist/antd.min.css";
import "./style.css";

export default () => {
  const [data, setData] = useState();
  const [graph, setGraph] = useState();
  const [selectedNodes, setSelectedNodes] = useState([]);

  /*
  *
  Load the graph JSON that is generated by MOZI's annotation service
  *
  */
  const handleFileUpload = (e) => {
    if (!e.target.files[0]) return;
    const reader = new FileReader();
    reader.onload = () => {
      const graphData = JSON.parse(reader.result);
      console.log("graphData", graphData);
      console.log(
        graphData.elements.nodes.reduce((acc, curr) => {
          return acc + curr.data.location.split(",").length;
        }, 0)
      );
      const curatedGraphData = getCuratedGraph(graphData.elements);
      const duplicatedGraph = duplicateMutlilocationNodes(curatedGraphData);
      setSelectedNodes([]);
      setData(graphData);
      setGraph(duplicatedGraph);
    };
    reader.readAsText(e.target.files[0]);
  };

  /*
  *
  handle click event on node
  *
  */
  const handleNodeClick = (node) => {
    const connectedNodes = getConnectedNodes(node, data);
    // add to the node's data, all nodes connected to it
    const selectedNode = { ...node, connectedNodes };
    // Check if the node is selected. If selected remove it from selected nodes list, otherwise add it to selected nodes list
    setSelectedNodes((nodes) =>
      nodes.find((n) => n.data.id === node.data.id)
        ? nodes.filter((n) => n.data.id !== node.data.id)
        : [...nodes, selectedNode]
    );
  };

  /*
   *
   *
   *
   */
  return (
    <div className="main-container">
      <nav className="navigation">
        <Typography.Title>Cell visualizer</Typography.Title>
        <input
          type="file"
          accept="application/JSON"
          onChange={handleFileUpload}
        />
      </nav>
      <div className="content">
        <Cell
          graph={graph}
          onNodeClick={handleNodeClick}
          selectedNodes={selectedNodes}
        />
      </div>
      <div className="definition">
        <Definition nodes={selectedNodes} />
      </div>
    </div>
  );
};
